window.FLASHCARDS = [
  { id: 1,  section: "Core",     front: "Max fill of a recovery cylinder?",                    back: "80% of water capacity (liquid expands with temp)." },
  { id: 2,  section: "Core",     front: "Passing score on each EPA 608 section?",              back: "70%." },
  { id: 3,  section: "Core",     front: "Which gas is used to pressure-test a system?",        back: "Dry nitrogen — never oxygen or compressed air." },
  { id: 4,  section: "Core",     front: "When did the CFC/HCFC venting ban start?",            back: "July 1, 1992." },
  { id: 5,  section: "Core",     front: "When did the HFC / substitute venting ban start?",    back: "November 15, 1995." },
  { id: 6,  section: "Core",     front: "DOT hydrostatic retest interval for recovery cylinders?", back: "Every 5 years." },
  { id: 7,  section: "Core",     front: "Recovery cylinder color code?",                       back: "Gray body, yellow shoulder (top)." },
  { id: 8,  section: "Core",     front: "ODP baseline refrigerant?",                           back: "R-11 (ODP = 1.0)." },
  { id: 9,  section: "Core",     front: "GWP baseline compound?",                              back: "Carbon dioxide (CO₂), GWP = 1.0." },
  { id: 10, section: "Core",     front: "R-22 production ban year in the US?",                 back: "2020." },
  { id: 11, section: "Core",     front: "Definition of 'reclaim'?",                            back: "Reprocess off-site to AHRI Standard 700 new-product spec. Only reclaimed refrigerant may be resold." },
  { id: 12, section: "Core",     front: "Do HFCs deplete ozone?",                              back: "No — zero ODP (they contain no chlorine). But many have high GWP." },
  { id: 13, section: "Core",     front: "Refrigerant + open flame = ?",                        back: "Phosgene, hydrofluoric acid, hydrochloric acid — highly toxic." },
  { id: 14, section: "Core",     front: "Section 608 covers which equipment?",                 back: "Stationary equipment. Motor vehicles fall under Section 609." },
  { id: 15, section: "Core",     front: "Who may legally buy bulk regulated refrigerant?",     back: "Only EPA 608-certified technicians (with the matching type)." },
  { id: 16, section: "Type I",   front: "Refrigerant limit that defines Type I?",              back: "5 lbs or less, hermetically sealed." },
  { id: 17, section: "Type I",   front: "Recovery target with working compressor (Type I)?",   back: "90% of charge OR 4 in. Hg vacuum." },
  { id: 18, section: "Type I",   front: "Recovery target with inoperative compressor (Type I)?", back: "80% of charge." },
  { id: 19, section: "Type I",   front: "Is system-dependent (passive) recovery allowed on split systems?", back: "No — only on small appliances (Type I)." },
  { id: 20, section: "Type I",   front: "Correct way to seal a process tube after service?",   back: "Pinch the process tube and braze closed — remove the saddle valve." },
  { id: 21, section: "Type II",  front: "Recovery target for high-pressure <200 lb?",          back: "0 psig." },
  { id: 22, section: "Type II",  front: "Recovery target for high-pressure ≥200 lb?",          back: "10 in. Hg vacuum." },
  { id: 23, section: "Type II",  front: "Deep-vacuum dehydration target?",                     back: "500 microns, held 10 minutes with pump isolated." },
  { id: 24, section: "Type II",  front: "How do you charge a zeotropic blend (400-series)?",   back: "As liquid — preserves the blend composition and prevents fractionation." },
  { id: 25, section: "Type II",  front: "Does a halide torch detect R-410A?",                  back: "No — halide torches need chlorine; R-410A is chlorine-free." },
  { id: 26, section: "Type II",  front: "Comfort cooling annual leak-rate limit?",             back: "10%." },
  { id: 27, section: "Type II",  front: "Commercial refrigeration leak-rate limit?",           back: "20%." },
  { id: 28, section: "Type II",  front: "Industrial process refrigeration leak-rate limit?",   back: "30%." },
  { id: 29, section: "Type II",  front: "Effect of non-condensables in a high-pressure system?", back: "Raises head pressure, reduces capacity, trips on high-pressure safety." },
  { id: 30, section: "Type III", front: "Recovery target for low-pressure chillers?",          back: "25 mm Hg absolute (~29 in. Hg vacuum)." },
  { id: 31, section: "Type III", front: "Rupture-disk setting on a low-pressure chiller?",     back: "15 psig." },
  { id: 32, section: "Type III", front: "Max warming temperature during recovery?",            back: "150 °F — heating blankets only, never open flame." },
  { id: 33, section: "Type III", front: "Max nitrogen pressure when leak-testing low-pressure?", back: "10 psig." },
  { id: 34, section: "Type III", front: "Most common Type III refrigerant in service today?",  back: "R-123." },
  { id: 35, section: "Type III", front: "ASHRAE safety group of R-123?",                       back: "B1 — higher toxicity, no flame propagation." },
  { id: 36, section: "Type III", front: "Why do low-pressure systems need a purge unit?",      back: "Low side runs below atmospheric — air and moisture leak IN, not refrigerant out. Purge removes them." }
];
